### ISSUE TITLE
Append attribute values instead of overwriting

### ISSUE THREAD

**Issue by xplosionmind** [aloskutov/eleventy-plugin-external-links#22]
**Is your feature request related to a problem? Please describe.**  
If there is a value in the `rel` original `<a>` tag, it is possible to choose whether to overwrite it or not. If the already present value is not overwritten, the values that the plugin should be adding are not even appended, only the present one exists.

**Describe the solution you'd like**
Instead of leaving the `rel` value as it is, or alternatively overwrite it altogether, it should be possible to append the default plugin values.

**Describe alternatives you've considered**
There is no alternative to overwriting or leaving the attribute as it is

**Example**
if the original value is `<a href='https://example.com' rel='me'>example</a>`, either it becomes `<a href='https://example.com' rel='noopener noreferrer external'>example</a>`, or it remains `<a href='https://example.com' rel='me noopener noreferrer external'>example</a>`. It should be `<a href='https://example.com' rel='me'>example</a>` instead.

**Comment by aloskutov** [comment]
fixed

**Comment by aloskutov** [comment]
Fixed.
