### ISSUE TITLE
New option to disable html tags wrapper

### ISSUE THREAD

**Issue by saiballo** [aloskutov/eleventy-plugin-external-links#74]
**Is your feature request related to a problem? Please describe.**
I need to generate some html partial template. When Eleventy compile the njk file the result is wrapped around doctype, html and body tag. I have only one option to disable the doctype but not others tag

**Describe the solution you'd like**
New option like "html wrapper" true| false

**Comment by saiballo** [comment]
any chance to verify this issue? :-)

**Comment by aloskutov** [comment]
I'm thinking of adding a `partial` option (default is `false`) which, when enabled, disables any manipulation of html code other than link processing.

**Comment by saiballo** [comment]
i think it would be perfect! thank you

**Comment by aloskutov** [comment]
There is one problem. The library I use for parsing html files `jsdom` can return only html with headers or fragment/partial without headers.

That is, if the `partial` option is active, then all parsed files will have no header (the content of the `<body>` tag is returned). And if the option is not active, the returned code will be wrapped in `<html><head></head></head><body>`.

So far I see one possible solution, but I haven't tested it yet. For partial once again plug in `eleventy-plugin-external-links` with parameters `{partial: true, ext: ['.partial']}`. That is, use an extension other than `.html` for partial, e.g. `.partial`. Not the best solution, but it doesn't break backwards compatibility.

P.S. I'll look at other libraries, maybe there is something more flexible than `jsdom`.

**Comment by aloskutov** [comment]
I'll think about other quick fixes today and tomorrow. I will test how much a working solution with two copies for `html` and `partial`. If everything works I will release version `1.5`.

**Comment by saiballo** [comment]
thank you... when you realese new version I 'll try it

**Comment by aloskutov** [comment]
The supposed solution didn't work. I changed the html parsing library, the current one has less influence on the html code, in particular it does not add missing `<html>` and `<body>` tags. But if they occur, it adds closing tags at the end of the code. It does not modify valid html code.

The `addDoctype` option is no longer active by default.

Test the current version. If there are problems we will look for a solution.

**Comment by saiballo** [comment]
I try it. It seems work perfectly! good job
